-- warning this will clear all tables in the database!! including users 

DROP TABLE IF EXISTS Classes;
DROP TABLE IF EXISTS Assignments;
DROP TABLE IF EXISTS Professors;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Ranks;
DROP TABLE IF EXISTS WillTakeItem;
DROP TABLE IF EXISTS Gives;
DROP TABLE IF EXISTS People;
DROP TABLE IF EXISTS Visits;
DROP TABLE IF EXISTS Printers;
DROP TABLE IF EXISTS AdjacentBuildings;
DROP TABLE IF EXISTS PlayerItems;
DROP TABLE IF EXISTS RoomItems;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Buildings;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS DialogueOptions;
DROP TABLE IF EXISTS Images;
DROP TABLE IF EXISTS UserCharacters;
DROP TABLE IF EXISTS Players;
DROP TABLE IF EXISTS Users;